// <auto-generated />
using System;
using Copa2022.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Copa2022.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220922141915_inicialCreate")]
    partial class inicialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Copa2022.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Copa2022.Models.Conta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("clienteid")
                        .HasColumnType("int");

                    b.Property<int?>("figurinhaid")
                        .HasColumnType("int");

                    b.Property<float>("quantidade")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("clienteid");

                    b.HasIndex("figurinhaid");

                    b.ToTable("contas");
                });

            modelBuilder.Entity("Copa2022.Models.Figurinha", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<float>("compra")
                        .HasColumnType("real");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pais")
                        .HasColumnType("int");

                    b.Property<int>("posicao")
                        .HasColumnType("int");

                    b.Property<int>("raridade")
                        .HasColumnType("int");

                    b.Property<float>("venda")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("figurinhas");
                });

            modelBuilder.Entity("Copa2022.Models.Transacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("contaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<int>("operacao")
                        .HasColumnType("int");

                    b.Property<float>("quantidade")
                        .HasColumnType("real");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("contaid");

                    b.ToTable("transacoes");
                });

            modelBuilder.Entity("Copa2022.Models.Conta", b =>
                {
                    b.HasOne("Copa2022.Models.Cliente", "cliente")
                        .WithMany("contas")
                        .HasForeignKey("clienteid");

                    b.HasOne("Copa2022.Models.Figurinha", "figurinha")
                        .WithMany("contas")
                        .HasForeignKey("figurinhaid");

                    b.Navigation("cliente");

                    b.Navigation("figurinha");
                });

            modelBuilder.Entity("Copa2022.Models.Transacao", b =>
                {
                    b.HasOne("Copa2022.Models.Conta", "conta")
                        .WithMany("transacoes")
                        .HasForeignKey("contaid");

                    b.Navigation("conta");
                });

            modelBuilder.Entity("Copa2022.Models.Cliente", b =>
                {
                    b.Navigation("contas");
                });

            modelBuilder.Entity("Copa2022.Models.Conta", b =>
                {
                    b.Navigation("transacoes");
                });

            modelBuilder.Entity("Copa2022.Models.Figurinha", b =>
                {
                    b.Navigation("contas");
                });
#pragma warning restore 612, 618
        }
    }
}
